"""SFT training script generated by /train-sft wizard."""
import asyncio
import art
from art.serverless.backend import ServerlessBackend
from art.utils.sft import train_sft_from_file


async def main():
    backend = ServerlessBackend()  # uses WANDB_API_KEY env var
    model = art.TrainableModel(
        name="sft-run-001",
        project="sft-project",
        base_model="OpenPipe/Qwen3-14B-Instruct",
    )
    await model.register(backend)

    await train_sft_from_file(
        model=model,
        file_path="dev/sft/dataset.jsonl",
        epochs=3,
        batch_size=2,
        peak_lr=2e-4,
        schedule_type="linear",
        warmup_ratio=0.6667,
        verbose=True,
    )

    # --- Training complete ---
    step = await model.get_step()
    inference_name = model.get_inference_name()
    client = model.openai_client()

    print("\n" + "=" * 60)
    print("SFT TRAINING COMPLETE")
    print("=" * 60)
    print(f"  Model:          {inference_name}")
    print(f"  Base model:     OpenPipe/Qwen3-14B-Instruct")
    print(f"  Training step:  {step}")
    print(f"  Inference URL:  {client.base_url}")
    print(f"  W&B run:        https://wandb.ai/<YOUR_TEAM>/sft-project/runs/sft-run-001")
    print("=" * 60)

    print("\n--- Python usage (openai SDK) ---\n")
    print(f'''\
from openai import OpenAI

client = OpenAI(
    base_url="{client.base_url}",
    api_key="not-needed",
)

response = client.chat.completions.create(
    model="{inference_name}",
    messages=[
        {{"role": "user", "content": "Your prompt here"}},
    ],
)
print(response.choices[0].message.content)
''')

    print("--- curl usage ---\n")
    print(f'''\
curl {client.base_url}chat/completions \\
  -H "Content-Type: application/json" \\
  -d '{{
    "model": "{inference_name}",
    "messages": [
      {{"role": "user", "content": "Your prompt here"}}
    ]
  }}'
''')

    await backend.close()


if __name__ == "__main__":
    asyncio.run(main())
