"""Distillation SFT script generated by /train-sft wizard."""
import asyncio
import json
import os

from dotenv import load_dotenv
from openai import AsyncOpenAI

import art
from art.serverless.backend import ServerlessBackend
from art.utils.sft import create_sft_dataset_iterator

load_dotenv()

DATASET_PATH = "dev/sft/dataset.jsonl"
TEACHER_MODEL = "z-ai/glm-5"
BASE_MODEL = "Qwen/Qwen3-30B-A3B-Instruct-2507"
PROJECT_NAME = "sft-project"
RUN_NAME = "pii-redactor-001"


async def main():
    # Set up teacher client (OpenRouter)
    teacher_client = AsyncOpenAI(
        api_key=os.environ["OPENROUTER_API_KEY"],
        base_url="https://openrouter.ai/api/v1",
    )

    # Read dataset and extract prompts
    rows = []
    with open(DATASET_PATH) as f:
        for line in f:
            rows.append(json.loads(line))

    print(f"Loaded {len(rows)} examples from {DATASET_PATH}")
    print(f"Generating teacher responses from {TEACHER_MODEL}...")

    # Generate teacher responses
    trajectories = []
    for i, row in enumerate(rows):
        messages = row["messages"]
        # Extract system + user messages (exclude assistant response)
        prompt_messages = [m for m in messages if m["role"] != "assistant"]

        # Build teacher request kwargs
        kwargs = {}
        if row.get("response_format"):
            kwargs["response_format"] = row["response_format"]

        completion = await teacher_client.chat.completions.create(
            model=TEACHER_MODEL,
            messages=prompt_messages,
            **kwargs,
        )

        teacher_response = completion.choices[0].message.content
        print(f"  [{i + 1}/{len(rows)}] Generated response ({len(teacher_response)} chars)")

        # Build trajectory: system + user + teacher assistant response
        messages_and_choices = prompt_messages + [
            {"role": "assistant", "content": teacher_response},
        ]

        trajectories.append(
            art.Trajectory(
                messages_and_choices=messages_and_choices,
                tools=row.get("tools") or None,
            )
        )

    print(f"\nCollected {len(trajectories)} trajectories. Starting training...")

    # Set up backend and model
    backend = ServerlessBackend()
    model = art.TrainableModel(
        name=RUN_NAME,
        project=PROJECT_NAME,
        base_model=BASE_MODEL,
    )
    await model.register(backend)

    # Train
    chunk_size = max(1, len(trajectories) // 20)
    for chunk in create_sft_dataset_iterator(
        trajectories,
        chunk_size=chunk_size,
        epochs=10,
        batch_size=2,
        peak_lr=2e-4,
        schedule_type="linear",
        warmup_ratio=0.2,
    ):
        await model.train_sft(chunk.trajectories, chunk.config, verbose=True)

    # --- Training complete ---
    step = await model.get_step()
    inference_name = model.get_inference_name()
    client = model.openai_client()

    print("\n" + "=" * 60)
    print("SFT TRAINING COMPLETE")
    print("=" * 60)
    print(f"  Model:          {inference_name}")
    print(f"  Base model:     {BASE_MODEL}")
    print(f"  Training step:  {step}")
    print(f"  Inference URL:  {client.base_url}")
    print("=" * 60)

    print("\n--- Python usage (openai SDK) ---\n")
    print(f'''\
from openai import OpenAI

client = OpenAI(
    base_url="{client.base_url}",
    api_key="not-needed",
)

response = client.chat.completions.create(
    model="{inference_name}",
    messages=[
        {{"role": "user", "content": "Your prompt here"}},
    ],
)
print(response.choices[0].message.content)
''')

    print("--- curl usage ---\n")
    print(f'''\
curl {client.base_url}chat/completions \\
  -H "Content-Type: application/json" \\
  -d '{{
    "model": "{inference_name}",
    "messages": [
      {{"role": "user", "content": "Your prompt here"}}
    ]
  }}'
''')

    await backend.close()


if __name__ == "__main__":
    asyncio.run(main())
