"""
train_ruler.py

GRPO fine-tuning of the IVR nav agent on all rows from the main training JSONL,
using RULER for reward scoring. Uses LocalBackend (GPU provisioned via SkyPilot).

Training data (Method...jsonl):
  - 108k rows, format: {input: {messages, tools}, output, ...}
  - Messages end with a user/IVR turn; we generate the next assistant turn
  - 300 rows held out as a validation split

Validation data (nav_1_3_24_gpt4o_relabeled...jsonl):
  - Format: {messages, tools, split}
  - Messages end with an assistant turn (the GPT-4o golden answer)
  - We strip the last turn -> context; golden answer = stripped turn
  - 300 rows sampled for validation

Validation every EVAL_EVERY steps:

  Holdout (no golden answer -- generated by model at step 0):
    - Generate our model's response + GPT-4.1 response
    - Score both with RULER (2-trajectory group)
    - Win rate = fraction where model RULER score > GPT-4.1 RULER score

  Test (nav_1_3_24, golden answer present):
    - Generate our model's response
    - Win rate = fraction where model's tool call matches the golden answer

RULER filtering: trajectory groups with reward std < MIN_REWARD_STD are dropped.

Usage:
    uv run python train_ruler.py           # local GPU
    sky launch sky-qwen35-rl.yaml          # remote GPU via SkyPilot

Requires:
    OPENAI_API_KEY env var
"""

import asyncio
from collections import Counter
import json
import os
from pathlib import Path
import random
import re
import statistics
import time
from typing import Any, Callable

from dotenv import load_dotenv
import httpx
from openai import AsyncOpenAI
from openai.types.chat import ChatCompletion
from openai.types.chat.chat_completion import Choice
from tqdm.asyncio import tqdm

import art
from art.local import LocalBackend
from art.metrics import track_api_cost
from art.rewards import ruler_score_group

load_dotenv()

os.environ.setdefault("WANDB_ENTITY", "coreweave1")


# Register gpt-5.4 pricing with litellm (not yet in its database)
import litellm

litellm.model_cost["openai/gpt-5.4"] = {
    "input_cost_per_token": 2.50 / 1_000_000,
    "cache_read_input_token_cost": 0.25 / 1_000_000,
    "output_cost_per_token": 15.00 / 1_000_000,
    "litellm_provider": "openai",
}
litellm.model_cost["openai/gpt-5.4-mini"] = {
    "input_cost_per_token": 0.75 / 1_000_000,
    "cache_read_input_token_cost": 0.075 / 1_000_000,
    "output_cost_per_token": 4.50 / 1_000_000,
    "litellm_provider": "openai",
}

# -- Configuration -------------------------------------------------------------

# When running via SkyPilot, files are mounted at /tmp/method-data/.
# Fall back to the local filenames for local runs.
TRAIN_PATH = Path(
    os.environ.get(
        "TRAIN_FILE",
        os.environ.get(
            "DEFAULT_TRAIN_FILE",
            "data/method_nav_prod_overnight_sample_50k.jsonl",
        ),
    )
)
TEST_PATH = Path(
    os.environ.get(
        "AUX_FILE",
        os.environ.get(
            "DEFAULT_AUX_FILE",
            "nav_1_3_24_gpt4o_relabeled - March 31, 2026 9_16_01 PM"
            " - c0fba847-9df3-4b8a-8190-5001cde7cc2e.jsonl",
        ),
    )
)

BASE_MODEL = os.environ.get("BASE_MODEL", "Qwen/Qwen3.5-35B-A3B")
MODEL_NAME = os.environ.get("MODEL_NAME", "ivr-nav-ruler-qwen3.5-049")
PROJECT_NAME = os.environ.get("PROJECT", "genesisfi")

GRPO_GROUP_SIZE = int(os.environ.get("GRPO_GROUP_SIZE", "16"))
BATCH_SIZE = int(os.environ.get("BATCH_SIZE", "60"))
LEARNING_RATE = float(os.environ.get("LEARNING_RATE", "1e-6"))
KL_COEFF = float(os.environ.get("KL_COEFF", "0"))
NUM_EPOCHS = int(os.environ.get("NUM_EPOCHS", "3"))
_TRAIN_LIMIT = os.environ.get("TRAIN_LIMIT")
TRAIN_LIMIT = int(_TRAIN_LIMIT) if _TRAIN_LIMIT else None
_MAX_STEPS = os.environ.get("MAX_STEPS")
MAX_STEPS = int(_MAX_STEPS) if _MAX_STEPS else None
SHUFFLE_SEED = 42

EVAL_EVERY = int(os.environ.get("EVAL_EVERY", "20"))
N_TEST_ROWS = int(os.environ.get("N_TEST_ROWS", "300"))
N_HOLDOUT_ROWS = int(os.environ.get("N_HOLDOUT_ROWS", "300"))

MAX_TOKENS = int(os.environ.get("MAX_TOKENS", "128"))
ROLLOUT_TEMPERATURE = float(os.environ.get("ROLLOUT_TEMPERATURE", "1.0"))
SAVE_CHECKPOINT = os.environ.get("SAVE_CHECKPOINT", "true").strip().lower() in {
    "1",
    "true",
    "yes",
    "on",
}
GPT41_MODEL = "gpt-4.1"  # baseline for holdout win-rate
RULER_JUDGE_MODEL = "openai/gpt-5.4"
RULER_EVAL_CONCURRENCY = 50  # max simultaneous RULER calls during eval

# Drop training groups where all RULER scores are nearly equal (no learning signal)
MIN_REWARD_STD = float(os.environ.get("MIN_REWARD_STD", "0.1"))
FORK_FROM_MODEL = os.environ.get("FORK_FROM_MODEL")
FORK_FROM_ARTIFACT = os.environ.get("FORK_FROM_ARTIFACT")
FORK_FROM_PROJECT = os.environ.get("FORK_FROM_PROJECT")
FORK_NOT_AFTER_STEP = os.environ.get("FORK_NOT_AFTER_STEP")

EVAL_LOG_DIR = Path(f"eval_logs/{MODEL_NAME}")

RULER_RUBRIC = """\
An AI agent is navigating a bank IVR phone system step-by-step.
Evaluate each trajectory and assign a continuous float score between 0.00 and 1.00.

CRITICAL INSTRUCTION: You MUST use two decimal places (e.g., 0.83, 0.42, 0.96).
DO NOT use clean round numbers like 0.80 or 1.00. Use the hundredths place to
reflect microscopic differences in efficiency, formatting, and logic.

SCORING BANDS:
- 0.91 to 0.99: Correct action that follows the system prompt instructions exactly.
  (Higher decimals for optimal efficiency).
- 0.61 to 0.89: Reasonable action but suboptimal (e.g., a safe wait when a
  clearer, faster action likely exists, or a correct action taken slightly late).
- 0.31 to 0.59: Wrong action that does not advance the goal but is not catastrophic.
- 0.01 to 0.29: Clearly wrong action (premature hangup, wrong digit, wait on
  active prompt). (Lower decimals for fatal errors).

CRITICAL RULES (priority order):
1. The agent's system prompt is authoritative: it specifies which fields to gather
   and often gives specific navigation instructions. Following them = high score.
2. IVR messages stream in real-time and may split across turns. A digit at the START
   of a message completes the PREVIOUS option, not the next one. Example:
   "press 4. for your balance..." means 4 = previous option, balance = next option
   (digit not yet spoken). COMMON MISTAKE: "press 4. for your balance, loan terms..."
   does NOT mean press 4 for balance.
3. hangup_and_extract({}) with empty args is normal. Do not penalize it.
4. wait() is ONLY high-scoring when the IVR is clearly mid-monologue AND required
   fields are still missing, or acting now would obviously be guessing. If a concrete
   better action exists now, wait should usually score no higher than 0.55. If the
   IVR asked a direct question, presented a menu, offered a concrete route, or all
   required fields are already gathered, wait should usually score in 0.01 to 0.20.
   Short ambiguous fragments can still justify wait, but unless the stream is clearly
   incomplete and unsafe to act on, that wait should usually stay below 0.90.
5. "No payment due" satisfies "next payment date and amount" ONLY, not "last payment."
   "Past due amount" is NOT "last payment." Be precise about field matching.
6. "No recent payments on file" DOES satisfy "last payment" (answer is "none"), so the
   agent should hangup_and_extract, not navigation_failed.
7. navigation_failed is acceptable for stuck loops (3+ repeated attempts), but NOT for
   ambiguous IVR fragments that might be mid-speech.
8. Judge ONLY the current action, not previous mistakes in the trajectory.
9. Voice menus ("you can say ...") may accept digit input, so do not penalize positional
   digit selection if the target option is correct.
10. Only reference instructions that ACTUALLY EXIST in the agent's system prompt.
    Do NOT hallucinate or infer instructions not explicitly written there.
"""
ALIGNED_TIE_EPSILON = float(os.environ.get("ALIGNED_TIE_EPSILON", "0.03"))


# -- Helpers --------------------------------------------------------------------


def load_jsonl(path: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def build_runtime_config() -> dict[str, Any]:
    return {
        "project": PROJECT_NAME,
        "model_name": MODEL_NAME,
        "base_model": BASE_MODEL,
        "grpo_group_size": GRPO_GROUP_SIZE,
        "batch_size": BATCH_SIZE,
        "learning_rate": LEARNING_RATE,
        "kl_coeff": KL_COEFF,
        "num_epochs": NUM_EPOCHS,
        "train_limit": TRAIN_LIMIT,
        "max_steps": MAX_STEPS,
        "shuffle_seed": SHUFFLE_SEED,
        "eval_every": EVAL_EVERY,
        "n_holdout_rows": N_HOLDOUT_ROWS,
        "n_test_rows": N_TEST_ROWS,
        "max_tokens": MAX_TOKENS,
        "rollout_temperature": ROLLOUT_TEMPERATURE,
        "save_checkpoint": SAVE_CHECKPOINT,
        "upload_checkpoints_to_wandb": _get_env_bool(
            "UPLOAD_CHECKPOINTS_TO_WANDB", False
        ),
        "upload_checkpoints_every_steps": int(
            os.environ.get("UPLOAD_CHECKPOINTS_EVERY_STEPS", "0")
        )
        or None,
        "ruler_judge_model": RULER_JUDGE_MODEL,
        "min_reward_std": MIN_REWARD_STD,
        "aligned_tie_epsilon": ALIGNED_TIE_EPSILON,
        "fork_from_artifact": FORK_FROM_ARTIFACT,
        "fork_from_model": FORK_FROM_MODEL,
        "fork_from_project": FORK_FROM_PROJECT,
        "fork_not_after_step": FORK_NOT_AFTER_STEP,
        "gpt41_model": GPT41_MODEL,
        "train_path": str(TRAIN_PATH),
        "test_path": str(TEST_PATH),
        "max_seq_length": int(os.environ.get("MAX_SEQ_LENGTH", "8192")),
        "load_in_4bit": _get_env_bool("LOAD_IN_4BIT", False),
        "load_in_16bit": _get_env_bool("LOAD_IN_16BIT", True),
        "gpu_memory_utilization": float(
            os.environ.get("GPU_MEMORY_UTILIZATION", "0.8")
        ),
        "enforce_eager": _get_env_bool("ENFORCE_EAGER", True),
        "max_model_len": int(os.environ.get("MAX_MODEL_LEN", "8192")),
        "max_num_seqs": int(os.environ.get("MAX_NUM_SEQS", "8")),
        "rollout_weights_mode": os.environ.get("ROLLOUT_WEIGHTS_MODE", "merged"),
        "trainer_gpu_ids": _get_env_int_list("TRAINER_GPU_IDS", [0]),
        "inference_gpu_ids": _get_env_int_list("INFERENCE_GPU_IDS", [1]),
        "eval_split_policy": "split == 'TEST' when available",
    }


def split_context_and_golden(
    messages: list[dict],
) -> tuple[list[dict], dict | None]:
    """Strip the last assistant turn if present; return (context, golden_msg)."""
    if messages and messages[-1].get("role") == "assistant":
        return messages[:-1], messages[-1]
    return messages, None


def choice_to_tool_name_and_args(choice: Choice) -> tuple[str, Any] | None:
    tool_calls = choice.message.tool_calls or []
    if not tool_calls:
        return None
    fn = tool_calls[0].function
    try:
        args = json.loads(fn.arguments) if fn.arguments else {}
    except Exception:
        args = fn.arguments
    return fn.name, args


def message_to_tool_name_and_args(msg: dict) -> tuple[str, Any] | None:
    tool_calls = msg.get("tool_calls") or []
    if not tool_calls:
        return None
    fn = tool_calls[0].get("function", {})
    try:
        args = json.loads(fn.get("arguments", "{}"))
    except Exception:
        args = fn.get("arguments", {})
    return fn.get("name", ""), args


def tool_calls_match(choice: Choice, golden_msg: dict) -> bool:
    """True if the model's tool call matches the golden answer (name + args)."""
    model_tc = choice_to_tool_name_and_args(choice)
    golden_tc = message_to_tool_name_and_args(golden_msg)
    if model_tc is None or golden_tc is None:
        return False
    return model_tc == golden_tc


def flatten_message_content(content: Any) -> str:
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        return " ".join(flatten_message_content(part) for part in content)
    if isinstance(content, dict):
        if "text" in content:
            return flatten_message_content(content["text"])
        if "content" in content:
            return flatten_message_content(content["content"])
        return " ".join(
            flatten_message_content(value)
            for value in content.values()
            if isinstance(value, (str, list, dict))
        )
    return ""


def normalize_text(text: str) -> str:
    return " ".join(text.lower().split())


def extract_user_texts(messages: list[dict]) -> list[str]:
    texts: list[str] = []
    for msg in messages:
        if msg.get("role") != "user":
            continue
        text = normalize_text(flatten_message_content(msg.get("content", "")))
        if text:
            texts.append(text)
    return texts


def count_pattern_hits(text: str, patterns: list[str]) -> int:
    return sum(1 for pattern in patterns if pattern in text)


def classify_eval_row(messages: list[dict], tools: list[dict]) -> dict[str, Any]:
    user_texts = extract_user_texts(messages)
    last_user_text = user_texts[-1] if user_texts else ""
    full_user_text = " ".join(user_texts)
    tool_names = {tool.get("function", {}).get("name", "") for tool in tools}

    keypad_entry = any(
        phrase in last_user_text
        for phrase in [
            "using your keypad",
            "using the keypad",
            "enter your account number",
            "enter your social security number",
            "enter your ssn",
            "enter your date of birth",
            "key in your",
            "please enter your",
        ]
    )
    explicit_menu = (
        bool(re.search(r"\bpress\s+\d+\b", last_user_text))
        or "you can say" in last_user_text
        or bool(re.search(r"\b(?:say|press)\s+[a-z0-9]", last_user_text))
    )
    direct_question = "?" in last_user_text or any(
        phrase in last_user_text
        for phrase in [
            "what you're calling about",
            "please tell me what you're calling about",
            "in a few words",
            "how can i help",
            "what can i help you with",
            "what are you calling about",
        ]
    )
    yes_no_prompt = any(
        phrase in last_user_text
        for phrase in [
            "is that correct",
            "yes or no",
            "would you like",
            "did i get that right",
            "if yes",
            "if no",
        ]
    )
    likely_stuck_loop = (
        count_pattern_hits(
            full_user_text,
            [
                "i'm sorry",
                "sorry, i",
                "didn't get that",
                "not sure i got that",
                "let's try again",
                "one more time",
                "invalid",
            ],
        )
        >= 2
    )

    balance_seen = any(
        phrase in full_user_text
        for phrase in [
            "current balance",
            "balance is $",
            "your balance is",
            "principal balance",
            "payoff amount",
            "available credit",
        ]
    )
    last_payment_seen = any(
        phrase in full_user_text
        for phrase in [
            "your last payment of",
            "last payment of $",
            "was received and credited",
            "was received on",
            "no recent payments on file",
        ]
    )
    next_payment_seen = any(
        phrase in full_user_text
        for phrase in [
            "next payment",
            "payment amount and due date",
            "no payment due",
            "there's no payment due",
            "past due amount",
        ]
    )
    extractable_now = balance_seen and (last_payment_seen or next_payment_seen)
    actionable_now = keypad_entry or explicit_menu or direct_question or yes_no_prompt

    return {
        "last_user_text": last_user_text,
        "actionable_now": actionable_now,
        "extractable_now": extractable_now,
        "keypad_entry": keypad_entry,
        "yes_no_prompt": yes_no_prompt,
        "likely_stuck_loop": likely_stuck_loop,
        "explicit_menu": explicit_menu,
        "direct_question": direct_question,
        "tool_names": sorted(name for name in tool_names if name),
    }


def percentile(values: list[float], p: float) -> float:
    if not values:
        return float("nan")
    sorted_values = sorted(values)
    if len(sorted_values) == 1:
        return sorted_values[0]
    pos = (len(sorted_values) - 1) * p
    lower = int(pos)
    upper = min(lower + 1, len(sorted_values) - 1)
    weight = pos - lower
    return sorted_values[lower] * (1 - weight) + sorted_values[upper] * weight


def safe_rate(numerator: int, denominator: int) -> float:
    if denominator <= 0:
        return 0.0
    return numerator / denominator


def is_say_action(action: str | None) -> bool:
    return bool(action and action.startswith("say_"))


def summarize_holdout_failure_modes(
    holdout_results: list[dict[str, Any]],
) -> dict[str, float]:
    if not holdout_results:
        return {}

    metrics: dict[str, float] = {}
    score_deltas = [float(r["score_delta"]) for r in holdout_results]
    metrics["compare/score_delta_mean"] = statistics.mean(score_deltas)
    metrics["compare/score_delta_median"] = statistics.median(score_deltas)
    metrics["compare/score_delta_p10"] = percentile(score_deltas, 0.10)
    metrics["compare/score_delta_p90"] = percentile(score_deltas, 0.90)

    supports = {
        "actionable_rows": sum(1 for r in holdout_results if r["actionable_now"]),
        "extractable_rows": sum(1 for r in holdout_results if r["extractable_now"]),
        "keypad_rows": sum(1 for r in holdout_results if r["keypad_entry"]),
        "yes_no_rows": sum(1 for r in holdout_results if r["yes_no_prompt"]),
        "stuck_loop_rows": sum(1 for r in holdout_results if r["likely_stuck_loop"]),
    }
    for name, count in supports.items():
        metrics[f"support/{name}"] = float(count)

    action_names = [
        "wait",
        "hangup_and_extract",
        "enter_digit",
        "say_no",
        "navigation_failed",
    ]
    for actor in ("model", "gpt41"):
        for action_name in action_names:
            metrics[f"action_rate/{actor}/{action_name}"] = safe_rate(
                sum(1 for r in holdout_results if r[f"{actor}_action"] == action_name),
                len(holdout_results),
            )

        metrics[f"failure/{actor}/wait_on_actionable_rate"] = safe_rate(
            sum(
                1
                for r in holdout_results
                if r["actionable_now"] and r[f"{actor}_action"] == "wait"
            ),
            supports["actionable_rows"],
        )
        metrics[f"failure/{actor}/wait_after_completion_rate"] = safe_rate(
            sum(
                1
                for r in holdout_results
                if r["extractable_now"] and r[f"{actor}_action"] == "wait"
            ),
            supports["extractable_rows"],
        )
        metrics[f"failure/{actor}/missed_extract_rate"] = safe_rate(
            sum(
                1
                for r in holdout_results
                if r["extractable_now"] and r[f"{actor}_action"] != "hangup_and_extract"
            ),
            supports["extractable_rows"],
        )
        metrics[f"failure/{actor}/premature_extract_rate"] = safe_rate(
            sum(
                1
                for r in holdout_results
                if (not r["extractable_now"])
                and r[f"{actor}_action"] == "hangup_and_extract"
            ),
            len(holdout_results) - supports["extractable_rows"],
        )
        metrics[f"failure/{actor}/speak_on_keypad_rate"] = safe_rate(
            sum(
                1
                for r in holdout_results
                if r["keypad_entry"] and is_say_action(r[f"{actor}_action"])
            ),
            supports["keypad_rows"],
        )
        metrics[f"failure/{actor}/say_no_misuse_rate"] = safe_rate(
            sum(
                1
                for r in holdout_results
                if (not r["yes_no_prompt"]) and r[f"{actor}_action"] == "say_no"
            ),
            len(holdout_results) - supports["yes_no_rows"],
        )
        metrics[f"failure/{actor}/navigation_failed_too_early_rate"] = safe_rate(
            sum(
                1
                for r in holdout_results
                if (not r["likely_stuck_loop"])
                and r[f"{actor}_action"] == "navigation_failed"
            ),
            len(holdout_results) - supports["stuck_loop_rows"],
        )
        metrics[f"failure/{actor}/wait_loss_rate"] = safe_rate(
            sum(
                1
                for r in holdout_results
                if r[f"{actor}_action"] == "wait"
                and r[f"{actor}_score"] + ALIGNED_TIE_EPSILON
                < r["model_score" if actor == "gpt41" else "gpt41_score"]
            ),
            sum(1 for r in holdout_results if r[f"{actor}_action"] == "wait"),
        )

    metrics["failure/compare/model_wait_vs_gpt41_action_rate"] = safe_rate(
        sum(
            1
            for r in holdout_results
            if r["model_action"] == "wait" and r["gpt41_action"] not in {None, "wait"}
        ),
        len(holdout_results),
    )
    metrics["failure/compare/gpt41_wait_vs_model_action_rate"] = safe_rate(
        sum(
            1
            for r in holdout_results
            if r["gpt41_action"] == "wait" and r["model_action"] not in {None, "wait"}
        ),
        len(holdout_results),
    )
    return metrics


def summarize_test_failure_modes(
    test_results: list[dict[str, Any]],
) -> dict[str, float]:
    if not test_results:
        return {}

    metrics: dict[str, float] = {}
    supports = {
        "actionable_rows": sum(1 for r in test_results if r["actionable_now"]),
        "extractable_rows": sum(1 for r in test_results if r["extractable_now"]),
        "keypad_rows": sum(1 for r in test_results if r["keypad_entry"]),
        "yes_no_rows": sum(1 for r in test_results if r["yes_no_prompt"]),
    }
    for name, count in supports.items():
        metrics[f"test/support/{name}"] = float(count)

    model_action_count = sum(1 for r in test_results if r["model_action"] is not None)
    metrics["test/failure/wrong_tool_rate"] = safe_rate(
        sum(
            1
            for r in test_results
            if r["model_action"] is not None
            and r["golden_action"] is not None
            and r["model_action"] != r["golden_action"]
        ),
        len(test_results),
    )
    metrics["test/failure/wrong_args_rate"] = safe_rate(
        sum(
            1
            for r in test_results
            if r["model_action"] is not None
            and r["golden_action"] is not None
            and r["model_action"] == r["golden_action"]
            and not r["match"]
        ),
        len(test_results),
    )
    metrics["test/failure/wait_on_actionable_rate"] = safe_rate(
        sum(
            1
            for r in test_results
            if r["actionable_now"] and r["model_action"] == "wait"
        ),
        supports["actionable_rows"],
    )
    metrics["test/failure/speak_on_keypad_rate"] = safe_rate(
        sum(
            1
            for r in test_results
            if r["keypad_entry"] and is_say_action(r["model_action"])
        ),
        supports["keypad_rows"],
    )
    metrics["test/failure/say_no_misuse_rate"] = safe_rate(
        sum(
            1
            for r in test_results
            if (not r["yes_no_prompt"]) and r["model_action"] == "say_no"
        ),
        len(test_results) - supports["yes_no_rows"],
    )
    metrics["test/failure/missed_extract_rate"] = safe_rate(
        sum(
            1
            for r in test_results
            if r["extractable_now"]
            and r["golden_action"] == "hangup_and_extract"
            and r["model_action"] != "hangup_and_extract"
        ),
        sum(
            1
            for r in test_results
            if r["extractable_now"] and r["golden_action"] == "hangup_and_extract"
        ),
    )
    metrics["test/failure/enter_digit_arg_mismatch_rate"] = safe_rate(
        sum(
            1
            for r in test_results
            if r["model_action"] == "enter_digit"
            and r["golden_action"] == "enter_digit"
            and not r["match"]
        ),
        sum(1 for r in test_results if r["golden_action"] == "enter_digit"),
    )
    metrics["test/action_rate/model/wait"] = safe_rate(
        sum(1 for r in test_results if r["model_action"] == "wait"),
        len(test_results),
    )
    metrics["test/action_rate/model/hangup_and_extract"] = safe_rate(
        sum(1 for r in test_results if r["model_action"] == "hangup_and_extract"),
        len(test_results),
    )
    metrics["test/action_rate/model/enter_digit"] = safe_rate(
        sum(1 for r in test_results if r["model_action"] == "enter_digit"),
        len(test_results),
    )
    metrics["test/support/model_action_rows"] = float(model_action_count)
    return metrics


def insert_tool_responses(messages: list[dict]) -> list[dict]:
    """Insert empty tool response messages after assistant tool_calls turns.

    GPT-4.1 requires every tool_calls message to be followed by a tool response.
    In IVR navigation, the model just fires-and-forgets tool calls so there are
    no response turns in the training data.
    """
    result = []
    for i, msg in enumerate(messages):
        result.append(msg)
        if msg.get("role") == "assistant" and msg.get("tool_calls"):
            next_role = messages[i + 1].get("role") if i + 1 < len(messages) else None
            if next_role != "tool":
                for tc in msg["tool_calls"]:
                    result.append(
                        {
                            "role": "tool",
                            "tool_call_id": tc["id"],
                            "content": "",
                        }
                    )
    return result


def extract_final_turn(trajectory: art.Trajectory) -> dict:
    """Extract the final assistant turn from a trajectory as a plain dict."""
    last = (
        trajectory.messages_and_choices[-1] if trajectory.messages_and_choices else None
    )
    if last is None:
        return {}
    if hasattr(last, "message"):
        msg = last.message
        tool_calls = []
        if msg.tool_calls:
            for tc in msg.tool_calls:
                tool_calls.append(
                    {"name": tc.function.name, "arguments": tc.function.arguments}
                )
        return {"content": msg.content, "tool_calls": tool_calls}
    tool_calls = [
        {
            "name": tc.get("function", {}).get("name", tc.get("name", "")),
            "arguments": tc.get("function", {}).get(
                "arguments", tc.get("arguments", "")
            ),
        }
        for tc in (last.get("tool_calls") or [])
    ]
    return {"content": last.get("content", ""), "tool_calls": tool_calls}


def get_ruler_reasoning(trajectory: art.Trajectory) -> str | None:
    """Extract RULER explanation from trajectory logs."""
    for entry in trajectory.logs or []:
        s = entry if isinstance(entry, str) else str(entry)
        if "RULER explanation:" in s:
            return s.split("RULER explanation:", 1)[1].strip()
    return None


def log_trajectory_samples(scored_groups: list[art.TrajectoryGroup], step: int) -> None:
    """Write and print trajectory final turns, rewards, and ruler reasoning."""
    log_dir = EVAL_LOG_DIR / "trajectories"
    log_dir.mkdir(exist_ok=True, parents=True)
    log_path = log_dir / f"step_{step:04d}.jsonl"
    print(f"\n  {'─' * 56}")
    print(f"  Trajectory samples (step {step})")
    print(f"  {'─' * 56}")
    with open(log_path, "w") as f:
        for group in scored_groups:
            scenario_id = (
                group.metadata.get("scenario_id", "") if group.metadata else ""
            )
            for i, traj in enumerate(group.trajectories):
                reasoning = get_ruler_reasoning(traj)
                final_turn = extract_final_turn(traj)
                entry = {
                    "step": step,
                    "scenario_id": scenario_id,
                    "trajectory_idx": i,
                    "reward": traj.reward,
                    "ruler_reasoning": reasoning,
                    "final_turn": final_turn,
                }
                f.write(json.dumps(entry) + "\n")
                tool_str = (
                    ", ".join(tc["name"] for tc in final_turn.get("tool_calls") or [])
                    or final_turn.get("content")
                    or "(empty)"
                )
                print(
                    f"  [{scenario_id}] traj {i}: reward={traj.reward:.3f}  action={tool_str}"
                )
                if reasoning:
                    print(f"    reasoning: {reasoning}")
    print(f"  Trajectory log -> {log_path}")


def group_reward_std(group: art.TrajectoryGroup) -> float:
    rewards = [t.reward for t in group.trajectories]
    if len(rewards) < 2:
        return 0.0
    try:
        return statistics.stdev(rewards)
    except statistics.StatisticsError:
        return 0.0


def row_scenario_id(row: dict[str, Any], fallback: str) -> str:
    return row.get("output", {}).get("id") or fallback


async def generate_response(
    client: AsyncOpenAI,
    model_name: str,
    messages: list[dict],
    tools: list[dict],
    n: int = 1,
) -> list[Choice]:
    for attempt in range(5):
        try:
            resp = await client.chat.completions.create(
                model=model_name,
                messages=messages,
                tools=tools or None,
                temperature=ROLLOUT_TEMPERATURE,
                max_tokens=MAX_TOKENS,
                n=n,
                extra_body={"chat_template_kwargs": {"enable_thinking": False}},
            )
            return resp.choices
        except Exception as exc:
            if "Already borrowed" in str(exc) and attempt < 4:
                await asyncio.sleep(2**attempt)
                continue
            print(f"    Warning: generation failed ({model_name}): {exc}")
            break
    return []


@track_api_cost(
    source="openai/gpt-4.1",
    provider="openai",
    model_name="openai/gpt-4.1",
)
async def generate_gpt41_response(
    client: AsyncOpenAI,
    messages: list[dict],
    tools: list[dict],
) -> ChatCompletion | None:
    """GPT-4.1 generation -- cost is tracked via @track_api_cost (full response returned)."""
    try:
        return await client.chat.completions.create(
            model=GPT41_MODEL,
            messages=insert_tool_responses(messages),
            tools=tools or None,
            max_tokens=MAX_TOKENS,
        )
    except Exception as exc:
        print(f"    Warning: GPT-4.1 generation failed: {exc}")
    return None


# -- Validation ----------------------------------------------------------------


async def run_eval(
    model: art.TrainableModel,
    backend: LocalBackend,
    model_client: AsyncOpenAI,
    get_inference_model_name: "Callable[[], str]",
    gpt41_client: AsyncOpenAI,
    holdout_rows: list[dict[str, Any]],
    test_rows: list[dict[str, Any]],
    step: int,
) -> None:
    """
    Holdout: RULER head-to-head -- model vs GPT-4.1 (2-trajectory group per row).
             Win rate = fraction where model RULER score > GPT-4.1 RULER score.

    Test:    Exact match -- model response vs golden assistant turn in the file.
             Win rate = fraction where tool call (name + args) matches golden.
    """
    print(f"\n{'─' * 60}")
    print(f"Eval at step {step}  (holdout={len(holdout_rows)}, test={len(test_rows)})")
    print(f"{'─' * 60}")

    await backend.persist_checkpoint(
        model=model,
        step=step,
        force=True,
        wait=False,
    )

    eval_builder = model.metrics_builder("eval")
    ruler_semaphore = asyncio.Semaphore(RULER_EVAL_CONCURRENCY)
    model_semaphore = asyncio.Semaphore(100)

    async def eval_holdout_row(row: dict[str, Any]) -> dict[str, Any] | None:
        messages: list[dict] = row["input"]["messages"]
        tools: list[dict] = row["input"].get("tools") or []
        row_features = classify_eval_row(messages, tools)

        async with model_semaphore:
            model_choices = await generate_response(
                model_client, get_inference_model_name(), messages, tools
            )
        model_choice = model_choices[0] if model_choices else None
        try:
            gpt41_resp = await generate_gpt41_response(gpt41_client, messages, tools)
        except Exception as exc:
            print(f"    Warning: GPT-4.1 cost tracking failed: {exc}")
            gpt41_resp = None
        gpt41_choice = (
            gpt41_resp.choices[0] if gpt41_resp and gpt41_resp.choices else None
        )
        if model_choice is None or gpt41_choice is None:
            return None

        group = art.TrajectoryGroup(
            [
                art.Trajectory(
                    messages_and_choices=list(messages) + [model_choice],
                    tools=tools,
                    reward=0.0,
                ),
                art.Trajectory(
                    messages_and_choices=list(messages) + [gpt41_choice],
                    tools=tools,
                    reward=0.0,
                ),
            ]
        )

        async with ruler_semaphore:
            scored = await ruler_score_group(
                group,
                RULER_JUDGE_MODEL,
                rubric=RULER_RUBRIC,
                swallow_exceptions=True,
                debug=False,
            )
        if scored is None:
            return None

        model_score = scored.trajectories[0].reward
        gpt41_score = scored.trajectories[1].reward
        score_delta = model_score - gpt41_score
        model_tc = choice_to_tool_name_and_args(model_choice)
        gpt41_tc = choice_to_tool_name_and_args(gpt41_choice)
        return {
            "model_score": model_score,
            "gpt41_score": gpt41_score,
            "score_delta": score_delta,
            "win": score_delta > ALIGNED_TIE_EPSILON,
            "tie": abs(score_delta) <= ALIGNED_TIE_EPSILON,
            "model_action": model_tc[0] if model_tc else None,
            "gpt41_action": gpt41_tc[0] if gpt41_tc else None,
            **row_features,
        }

    async def eval_test_row(row: dict[str, Any]) -> dict[str, Any] | None:
        messages: list[dict] = row["messages"]
        tools: list[dict] = row.get("tools") or []

        context, golden_msg = split_context_and_golden(messages)
        if golden_msg is None:
            return None
        row_features = classify_eval_row(context, tools)

        async with model_semaphore:
            model_choices = await generate_response(
                model_client, get_inference_model_name(), context, tools
            )
        model_choice = model_choices[0] if model_choices else None
        if model_choice is None:
            return None

        gpt41_resp = await generate_gpt41_response(gpt41_client, context, tools)
        gpt41_choice = (
            gpt41_resp.choices[0] if gpt41_resp and gpt41_resp.choices else None
        )

        matched = tool_calls_match(model_choice, golden_msg)
        model_tc = choice_to_tool_name_and_args(model_choice)
        golden_tc = message_to_tool_name_and_args(golden_msg)
        gpt41_tc = choice_to_tool_name_and_args(gpt41_choice) if gpt41_choice else None
        tie = (
            model_tc == gpt41_tc
            if (model_tc is not None and gpt41_tc is not None)
            else False
        )
        return {
            "match": matched,
            "tie": tie,
            "model_action": model_tc[0] if model_tc else None,
            "golden_action": golden_tc[0] if golden_tc else None,
            **row_features,
        }

    with eval_builder.activate_context():
        with eval_builder.measure("time/step_eval_s"):
            holdout_results, test_results = await asyncio.gather(
                tqdm.gather(
                    *[eval_holdout_row(r) for r in holdout_rows],
                    desc=f"Eval (holdout) step {step}",
                ),
                tqdm.gather(
                    *[eval_test_row(r) for r in test_rows],
                    desc=f"Eval (test)    step {step}",
                ),
            )

    holdout_results = [r for r in holdout_results if r is not None]
    test_results = [r for r in test_results if r is not None]

    if holdout_results:
        wins = sum(1 for r in holdout_results if r["win"])
        ties = sum(1 for r in holdout_results if r["tie"])
        h_n = len(holdout_results)
        h_win_rate = wins / h_n
        h_tie_rate = ties / h_n
        h_win_tie_rate = (wins + ties) / h_n
        holdout_failure_metrics = summarize_holdout_failure_modes(holdout_results)
    else:
        h_win_rate, h_tie_rate, h_win_tie_rate, h_n = (
            float("nan"),
            float("nan"),
            float("nan"),
            0,
        )
        holdout_failure_metrics = {}

    if test_results:
        t_match_rate = sum(r["match"] for r in test_results) / len(test_results)
        t_tie_rate = sum(r["tie"] for r in test_results) / len(test_results)
        t_n = len(test_results)
        test_failure_metrics = summarize_test_failure_modes(test_results)
    else:
        t_match_rate, t_tie_rate, t_n = float("nan"), float("nan"), 0
        test_failure_metrics = {}

    print(f"  Holdout RULER win rate      : {h_win_rate:.1%}  (n={h_n})")
    print(f"  Holdout RULER tie rate      : {h_tie_rate:.1%}  (n={h_n})")
    print(f"  Holdout RULER win+tie rate  : {h_win_tie_rate:.1%}  (n={h_n})")
    if holdout_failure_metrics:
        print(
            "  Failure modes              : "
            f"model wait/actionable={holdout_failure_metrics.get('failure/model/wait_on_actionable_rate', 0.0):.1%}  "
            f"model missed extract={holdout_failure_metrics.get('failure/model/missed_extract_rate', 0.0):.1%}  "
            f"model speak/keypad={holdout_failure_metrics.get('failure/model/speak_on_keypad_rate', 0.0):.1%}"
        )
        print(
            "                               "
            f"gpt41 wait/actionable={holdout_failure_metrics.get('failure/gpt41/wait_on_actionable_rate', 0.0):.1%}  "
            f"gpt41 missed extract={holdout_failure_metrics.get('failure/gpt41/missed_extract_rate', 0.0):.1%}  "
            f"delta mean={holdout_failure_metrics.get('compare/score_delta_mean', float('nan')):.3f}"
        )
    print(f"  Test    match rate          : {t_match_rate:.1%}  (n={t_n})")
    print(f"  Test    tie rate            : {t_tie_rate:.1%}  (n={t_n})")
    if test_failure_metrics:
        print(
            "  Test failures              : "
            f"wrong tool={test_failure_metrics.get('test/failure/wrong_tool_rate', 0.0):.1%}  "
            f"wrong args={test_failure_metrics.get('test/failure/wrong_args_rate', 0.0):.1%}  "
            f"wait/actionable={test_failure_metrics.get('test/failure/wait_on_actionable_rate', 0.0):.1%}"
        )

    await model.log(
        [],
        metrics={
            "ruler_win_rate": h_win_rate,
            "ruler_tie_rate": h_tie_rate,
            "ruler_win_tie_rate": h_win_tie_rate,
            **holdout_failure_metrics,
        },
        step=step,
        split="val",
    )
    await model.log(
        [],
        metrics={
            "test/golden_match_rate": t_match_rate,
            "test/tie_rate": t_tie_rate,
            **test_failure_metrics,
        },
        step=step,
        split="test",
    )

    EVAL_LOG_DIR.mkdir(exist_ok=True, parents=True)
    log_path = EVAL_LOG_DIR / f"step_{step:04d}.json"
    with open(log_path, "w") as f:
        json.dump(
            {
                "step": step,
                "holdout": {
                    "win_rate": h_win_rate,
                    "tie_rate": h_tie_rate,
                    "win_tie_rate": h_win_tie_rate,
                    "n": h_n,
                },
                "test": {"match_rate": t_match_rate, "n": t_n},
                "holdout_diagnostics": holdout_failure_metrics,
                "test_diagnostics": test_failure_metrics,
            },
            f,
        )
    print(f"  Logged -> {log_path}")


# -- Training loop -------------------------------------------------------------


async def train(model: art.TrainableModel) -> None:
    runtime_config = build_runtime_config()
    print("\nRuntime config:")
    print(json.dumps(runtime_config, indent=2, sort_keys=True))
    model.update_wandb_config(runtime_config)

    backend = LocalBackend()
    gpt41_http_client = httpx.AsyncClient(timeout=90)
    gpt41_client = AsyncOpenAI(http_client=gpt41_http_client)

    try:
        await model.register(
            backend,
            _openai_client_config={
                "server_args": {
                    "tool_call_parser": "qwen3_coder",
                    "enable_auto_tool_choice": True,
                }
            },
        )

        if FORK_FROM_MODEL or FORK_FROM_ARTIFACT:
            await backend._experimental_fork_checkpoint(
                model=model,
                from_model=FORK_FROM_MODEL,
                from_project=FORK_FROM_PROJECT or PROJECT_NAME,
                from_wandb_artifact=FORK_FROM_ARTIFACT,
                not_after_step=int(FORK_NOT_AFTER_STEP)
                if FORK_NOT_AFTER_STEP
                else None,
                verbose=True,
            )

        model_client = model.openai_client()

        # -- Test inference after LoRA seeding ----------------------------------
        print("\nRunning test inference to verify LoRA loaded correctly...")
        try:
            with open(TRAIN_PATH) as f:
                for i, line in enumerate(f):
                    if i == 0:
                        test_inp = json.loads(line)["input"]
                    if i == 1:
                        test_inp["tools"] = json.loads(line)["input"]["tools"]
                        break
            test_resp = await model_client.chat.completions.create(
                model=backend._model_inference_name(model),
                messages=test_inp["messages"],
                tools=test_inp["tools"] or None,
                tool_choice="auto",
                temperature=0,
                max_tokens=MAX_TOKENS,
                logprobs=True,
                extra_body={"chat_template_kwargs": {"enable_thinking": False}},
            )
            choices = test_resp.choices
            if choices:
                token_logprobs = []
                if choices[0].logprobs and choices[0].logprobs.content:
                    token_logprobs = [
                        t.model_dump() for t in choices[0].logprobs.content
                    ]
                if token_logprobs:
                    raw_bytes = b"".join(
                        bytes(t["bytes"]) for t in token_logprobs if t.get("bytes")
                    )
                    if raw_bytes:
                        print("\nRaw decoded output (from bytes):")
                        print(raw_bytes.decode("utf-8", errors="replace"))
                    else:
                        print("\nRaw decoded output (from token strings):")
                        print("".join(t.get("token", "") for t in token_logprobs))
                else:
                    print("\nNo logprobs returned.")
                    print("Raw logprobs field:", choices[0].logprobs)
            else:
                print("  Test inference returned no choices")
        except Exception as exc:
            print(f"  Test inference failed (non-fatal): {exc}")

        def get_inference_model_name() -> str:
            """Return the current LoRA checkpoint name for vLLM inference."""
            return backend._model_inference_name(model)

        print(f"Local vLLM serving model as: {get_inference_model_name()!r}")

        # -- Load and split training data ---------------------------------------
        print(f"Loading training data from {TRAIN_PATH} ...")
        all_train = load_jsonl(TRAIN_PATH)
        print(f"  {len(all_train)} rows loaded")

        rng = random.Random(SHUFFLE_SEED)
        rng.shuffle(all_train)

        holdout_rows = all_train[:N_HOLDOUT_ROWS]
        train_rows = all_train[N_HOLDOUT_ROWS:]
        if TRAIN_LIMIT is not None:
            train_rows = train_rows[:TRAIN_LIMIT]
        print(f"  {len(train_rows)} train / {len(holdout_rows)} holdout")

        # -- Load and sample test data ------------------------------------------
        print(f"Loading test data from {TEST_PATH} ...")
        all_test = load_jsonl(TEST_PATH)
        split_counts = Counter(
            str(row.get("split", "<missing>")) for row in all_test if "split" in row
        )
        if split_counts:
            print(f"  split distribution: {dict(split_counts)}")
            candidate_test_rows = [
                row for row in all_test if row.get("split") == "TEST"
            ]
            if not candidate_test_rows:
                raise ValueError(
                    f"Expected at least one split == 'TEST' row in {TEST_PATH}, "
                    f"found {dict(split_counts)}"
                )
            print(
                f"  using split == 'TEST' rows only: "
                f"{len(candidate_test_rows)} / {len(all_test)}"
            )
        else:
            candidate_test_rows = all_test
            print("  no split field found; using the full eval file")
        rng_test = random.Random(SHUFFLE_SEED + 1)
        rng_test.shuffle(candidate_test_rows)
        test_rows = candidate_test_rows[:N_TEST_ROWS]
        print(
            f"  {len(test_rows)} test rows sampled from "
            f"{len(candidate_test_rows)} candidate rows "
            f"({len(all_test)} total rows)"
        )

        # -- Training loop ------------------------------------------------------

        last_eval_step = -EVAL_EVERY
        step = await model.get_step()
        stop_training = False

        for epoch in range(NUM_EPOCHS):
            print(f"\n{'=' * 60}")
            print(f"Epoch {epoch + 1}/{NUM_EPOCHS}  ({len(train_rows)} rows)")
            print(f"{'=' * 60}")

            epoch_rows = train_rows.copy()
            rng_epoch = random.Random(SHUFFLE_SEED + epoch)
            rng_epoch.shuffle(epoch_rows)

            for batch_start in range(0, len(epoch_rows), BATCH_SIZE):
                batch = epoch_rows[batch_start : batch_start + BATCH_SIZE]
                step = await model.get_step()
                if MAX_STEPS is not None and step >= MAX_STEPS:
                    print(f"Reached MAX_STEPS={MAX_STEPS}; stopping training loop.")
                    stop_training = True
                    break

                print(
                    f"\n--- Step {step} | "
                    f"rows {batch_start}--{batch_start + len(batch) - 1} "
                    f"(epoch {epoch + 1}) ---"
                )

                # -- Periodic eval ----------------------------------------------
                if (step - last_eval_step) >= EVAL_EVERY:
                    await run_eval(
                        model,
                        backend,
                        model_client,
                        get_inference_model_name,
                        gpt41_client,
                        holdout_rows,
                        test_rows,
                        step,
                    )
                    last_eval_step = step

                # -- Build + score trajectory groups ----------------------------
                scenario_ids = [
                    row_scenario_id(r, f"train_{batch_start + i}")
                    for i, r in enumerate(batch)
                ]

                train_builder = model.metrics_builder("train")

                async def build_group(
                    row: dict[str, Any],
                    scenario_id: str,
                ) -> art.TrajectoryGroup | None:
                    messages: list[dict] = row["input"]["messages"]
                    tools: list[dict] = row["input"].get("tools") or []
                    context, _ = split_context_and_golden(messages)

                    choices = await generate_response(
                        model_client,
                        get_inference_model_name(),
                        context,
                        tools,
                        n=GRPO_GROUP_SIZE,
                    )
                    if not choices:
                        return None

                    group = art.TrajectoryGroup(
                        [
                            art.Trajectory(
                                messages_and_choices=context + [choice],
                                tools=tools,
                                reward=0.0,
                            )
                            for choice in choices
                        ]
                    )
                    group.metadata["scenario_id"] = scenario_id
                    return group

                async def score_group(
                    group: art.TrajectoryGroup,
                ) -> art.TrajectoryGroup | None:
                    non_tool_trajs: list[art.Trajectory] = []
                    for t in group.trajectories:
                        if not t.messages_and_choices[-1].message.tool_calls:
                            non_tool_trajs.append(t)

                    for t in non_tool_trajs:
                        group.trajectories.remove(t)

                    scored = await ruler_score_group(
                        group,
                        RULER_JUDGE_MODEL,
                        rubric=RULER_RUBRIC,
                        swallow_exceptions=True,
                        debug=False,
                    )

                    if scored is None:
                        return None

                    for t in non_tool_trajs:
                        t.reward = -0.1
                        scored.trajectories.append(t)

                    if group_reward_std(scored) < MIN_REWARD_STD:
                        return None
                    return scored

                with train_builder.activate_context():
                    with train_builder.measure("time/step_actor_s"):
                        raw_groups = await asyncio.gather(
                            *[
                                build_group(r, sid)
                                for r, sid in zip(batch, scenario_ids)
                            ]
                        )
                        raw_groups = [g for g in raw_groups if g is not None]

                        scored_groups = await asyncio.gather(
                            *[score_group(g) for g in raw_groups]
                        )
                        scored_groups = [g for g in scored_groups if g is not None]

                train_builder.add_data(
                    step_num_scenarios=len(batch),
                    scenario_ids=scenario_ids,
                )

                print(
                    f"  Valid groups after RULER filter: "
                    f"{len(scored_groups)}/{len(batch)}"
                )
                if not scored_groups:
                    print("  No valid groups, skipping step.")
                    continue

                log_trajectory_samples(scored_groups, step)

                # -- Train ------------------------------------------------------
                result = await backend.train(
                    model=model,
                    trajectory_groups=scored_groups,
                    learning_rate=LEARNING_RATE,
                    # kl_penalty_coef=KL_COEFF,
                    # kl_penalty_reference_step=0,
                    save_checkpoint=SAVE_CHECKPOINT,
                )
                await model.log(
                    scored_groups,
                    metrics=result.metrics,
                    step=result.step,
                    split="train",
                )

                metrics_str = "  ".join(
                    f"{k}={v:.4f}"
                    for k, v in result.metrics.items()
                    if isinstance(v, float)
                )
                print(f"  Step {result.step} metrics: {metrics_str}")
            if stop_training:
                break

        # Final eval
        step = await model.get_step()
        await run_eval(
            model,
            backend,
            model_client,
            get_inference_model_name,
            gpt41_client,
            holdout_rows,
            test_rows,
            step,
        )
        print("\nTraining complete.")
    finally:
        await gpt41_http_client.aclose()
        await backend.close()


def _get_env_bool(name: str, default: bool) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def _get_env_int_list(name: str, default: list[int]) -> list[int]:
    value = os.environ.get(name)
    if value is None:
        return default
    return [int(p.strip()) for p in value.split(",") if p.strip()]


if __name__ == "__main__":
    model = art.TrainableModel(
        name=MODEL_NAME,
        project=PROJECT_NAME,
        base_model=BASE_MODEL,
        config=None,
        report_metrics=["wandb"],
    )
    model._internal_config = art.dev.InternalModelConfig(
        init_args=art.dev.InitArgs(
            max_seq_length=int(os.environ.get("MAX_SEQ_LENGTH", "8192")),
            load_in_4bit=_get_env_bool("LOAD_IN_4BIT", False),
            load_in_16bit=_get_env_bool("LOAD_IN_16BIT", True),
        ),
        engine_args=art.dev.EngineArgs(
            gpu_memory_utilization=float(
                os.environ.get("GPU_MEMORY_UTILIZATION", "0.8")
            ),
            enforce_eager=_get_env_bool("ENFORCE_EAGER", True),
            max_model_len=int(os.environ.get("MAX_MODEL_LEN", "8192")),
            max_num_seqs=int(os.environ.get("MAX_NUM_SEQS", "8")),
        ),
        rollout_weights_mode=os.environ.get("ROLLOUT_WEIGHTS_MODE", "merged"),
        trainer_gpu_ids=_get_env_int_list("TRAINER_GPU_IDS", [0]),
        inference_gpu_ids=_get_env_int_list("INFERENCE_GPU_IDS", [1]),
    )
    asyncio.run(train(model))
